#!/usr/bin/env bash
#
# Turns a bare Arch install into this exact rice.
#
#   git clone <repo> && cd <repo> && ./install.sh
#
# Existing configs are backed up as .bak-<timestamp>; nothing is deleted
# silently. Safe to run more than once.

set -uo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
STAMP="$(date +%Y%m%d-%H%M%S)"
THEME="${QS_THEME:-catppuccin-mocha}"
FAILED=()

say()  { printf '\n\033[1;35m==>\033[0m \033[1m%s\033[0m\n' "$*"; }
ok()   { printf '  \033[1;32m✓\033[0m %s\n' "$*"; }
warn() { printf '  \033[1;33m!\033[0m %s\n' "$*"; FAILED+=("$*"); }

[[ $EUID -eq 0 ]] && { echo "Do not run install.sh as root (it calls sudo when needed)."; exit 1; }
command -v pacman >/dev/null || { echo "This script targets Arch-based systems."; exit 1; }

# ============================================================
# 1. Packages
# ============================================================

# Compositor and session
CORE=(hyprland hyprpaper hyprlock uwsm xdg-desktop-portal-hyprland
      polkit-kde-agent gnome-keyring qt5-wayland qt6-wayland)

# Bar, terminal, shell and everyday apps
DESKTOP=(kitty fish fastfetch dunst btop neovim yazi dolphin
         gnome-calculator gnome-text-editor gnome-characters gcolor3 gwenview
         pavucontrol)

# The shell itself and clipboard persistence — both in the official repos now
SHELL_PKGS=(quickshell wl-clip-persist)

# Commands the qs-* scripts call directly
TOOLS=(grim slurp wl-clipboard cliphist imagemagick ffmpeg python zenity
       poppler ddcutil jq rsync socat wireplumber pipewire pipewire-pulse
       xdg-user-dirs unzip zip libnotify glib2 fontconfig xorg-xhost)

# Look and feel. breeze-cursors is required: the Hyprland env sets
# XCURSOR_THEME=breeze_cursors, without it you get the default X cursor.
#
# Both Nerd Fonts ship on purpose: config/quickshell/font.conf picks one, and
# qs-font refuses a family fontconfig cannot see. otf-monaspace-nerd is the
# current choice (Monaspace Argon); ttf-jetbrains-mono-nerd stays as the
# fallback the code defaults to when font.conf is missing or unreadable.
LOOKS=(papirus-icon-theme breeze-cursors
       ttf-jetbrains-mono-nerd otf-monaspace-nerd
       noto-fonts noto-fonts-emoji kvantum qt6ct gnome-themes-extra
       adwaita-icon-theme)

# AUR — only what is not in the repos
AUR=(mpvpaper pwvucontrol zen-browser-bin)

say "Installing repository packages"
sudo pacman -Syu --needed --noconfirm \
    "${CORE[@]}" "${DESKTOP[@]}" "${SHELL_PKGS[@]}" "${TOOLS[@]}" "${LOOKS[@]}" \
    || warn "some repository packages failed to install"

if ! command -v yay >/dev/null 2>&1; then
    say "Installing yay (needed for AUR packages)"
    sudo pacman -S --needed --noconfirm git base-devel || warn "base-devel failed"
    tmp="$(mktemp -d)"
    if git clone --depth 1 https://aur.archlinux.org/yay-bin.git "$tmp/yay" \
       && (cd "$tmp/yay" && makepkg -si --noconfirm); then ok "yay installed"
    else warn "yay could not be installed — install AUR packages manually"; fi
    rm -rf "$tmp"
fi

if command -v yay >/dev/null 2>&1; then
    say "Installing AUR packages"
    for p in "${AUR[@]}"; do
        yay -S --needed --noconfirm "$p" || warn "AUR: $p failed"
    done
    # Optional — the setup works fine without it
    yay -S --needed --noconfirm youtube-music-desktop-app >/dev/null 2>&1 \
        && ok "youtube-music-desktop-app" || true
fi

# ============================================================
# 2. Configs
# ============================================================

backup() { [[ -e "$1" || -L "$1" ]] && mv "$1" "$1.bak-$STAMP" && warn "backed up: ${1/#$HOME/\~}.bak-$STAMP"; return 0; }

place_dir() {   # place_dir <repo-relative> <destination>
    local src="$REPO/$1" dst="$2"
    [[ -d "$src" ]] || return 0
    mkdir -p "$(dirname "$dst")"
    backup "$dst"
    cp -r "$src" "$dst" && ok "${dst/#$HOME/\~}"
}

place_file() {
    local src="$REPO/$1" dst="$2"
    [[ -f "$src" ]] || return 0
    mkdir -p "$(dirname "$dst")"
    backup "$dst"
    cp "$src" "$dst" && ok "${dst/#$HOME/\~}"
}

say "Installing configs"
mkdir -p "$HOME/.config" "$HOME/.local/bin" "$HOME/.local/share"

for d in hypr quickshell kitty fish fastfetch dunst nvim qt6ct btop; do
    place_dir "config/$d" "$HOME/.config/$d"
done

# Kvantum: the catppuccin source theme is required — qs-theme-kvantum derives
# every other theme from it by recolouring
place_dir "config/Kvantum" "$HOME/.config/Kvantum"

# Dolphin / KDE. kdeglobals is intentionally absent: qs-theme-kde generates it
place_file "config/dolphinrc"      "$HOME/.config/dolphinrc"
place_file "config/kiorc"          "$HOME/.config/kiorc"
place_file "config/kservicemenurc" "$HOME/.config/kservicemenurc"

# GTK: only settings.ini, gtk.css is generated by qs-theme-gtk
mkdir -p "$HOME/.config/gtk-3.0" "$HOME/.config/gtk-4.0"
place_file "config/gtk-3.0/settings.ini" "$HOME/.config/gtk-3.0/settings.ini"
place_file "config/gtk-4.0/settings.ini" "$HOME/.config/gtk-4.0/settings.ini"

# Some configs cannot express $HOME and hold an absolute path — most
# importantly dunstrc's `script = …/dunst-forward`. If that path is wrong the
# notification proxy never runs and NO notification is ever displayed.
say "Rewriting absolute paths for this user"
mapfile -t patched < <(grep -rl '/home/mrlemon' \
    "$HOME/.config/dunst" "$HOME/.config/qt6ct" "$HOME/.config/fish" \
    "$HOME/.config/hypr" "$HOME/.config/quickshell" 2>/dev/null)
if ((${#patched[@]})); then
    sed -i "s|/home/mrlemon|$HOME|g" "${patched[@]}"
    ok "${#patched[@]} file(s) updated"
else
    ok "nothing to rewrite"
fi

# ============================================================
# 3. Fonts, themes, icons
# ============================================================

say "Fonts and themes"
for d in fonts themes icons applications dolphin kxmlgui5; do
    [[ -d "$REPO/local/share/$d" ]] || continue
    mkdir -p "$HOME/.local/share/$d"
    cp -rn "$REPO/local/share/$d/." "$HOME/.local/share/$d/" 2>/dev/null
    ok "~/.local/share/$d"
done
# Without this the runcat font and the nerd-font icons in the bar stay blank
fc-cache -f >/dev/null 2>&1 && ok "font cache rebuilt"

# ============================================================
# 4. Scripts
# ============================================================

say "Scripts into ~/.local/bin"
cp "$REPO"/bin/* "$HOME/.local/bin/" 2>/dev/null
chmod +x "$HOME"/.local/bin/qs-* "$HOME"/.local/bin/dunst-* "$HOME"/.local/bin/screenshot 2>/dev/null
ok "$(ls "$REPO"/bin | wc -l) scripts"

case ":$PATH:" in
    *":$HOME/.local/bin:"*) ;;
    *) warn "~/.local/bin is not on PATH — add this to your shell profile:"
       printf '        export PATH="$HOME/.local/bin:$PATH"\n' ;;
esac

# ============================================================
# 5. Wallpapers
# ============================================================

say "Wallpapers"
mkdir -p "$HOME/Pictures/Screenshots" "$HOME/Pictures/Wallpapers"

# -n: never overwrite an existing file, so re-running keeps what you added
if [[ -f "$REPO/wallpapers.zip" ]]; then
    unzip -qn "$REPO/wallpapers.zip" -d "$HOME/Pictures/Wallpapers" \
        && ok "wallpapers.zip extracted" || warn "wallpapers.zip failed"
fi

# The animated ones are a SPLIT archive (.z01, .z02, … + .zip) because the
# videos add up to ~200MB and GitHub rejects single files over 100MB.
# They have to be joined back into one archive before unzip can read them.
if [[ -f "$REPO/wallpapers-animated.zip" ]]; then
    if compgen -G "$REPO/wallpapers-animated.z0*" >/dev/null; then
        joined="$(mktemp -u --suffix=.zip)"
        if zip -qs 0 "$REPO/wallpapers-animated.zip" --out "$joined" 2>/dev/null; then
            unzip -qn "$joined" -d "$HOME/Pictures/Wallpapers" \
                && ok "animated wallpapers extracted" || warn "animated archive failed"
            rm -f "$joined"
        else
            warn "could not join the split animated archive (are all .z0* parts present?)"
        fi
    else
        unzip -qn "$REPO/wallpapers-animated.zip" -d "$HOME/Pictures/Wallpapers" \
            && ok "animated wallpapers extracted" || warn "animated archive failed"
    fi
fi
ok "$(find "$HOME/Pictures/Wallpapers" -type f | wc -l) wallpapers in total"

# A folder per theme, plus its Animated/ subfolder (qs-wallpaper matches names
# fuzzily, so CatpuccinMocha matches catppuccin-mocha)
if [[ -x "$HOME/.local/bin/qs-palette" ]]; then
    while read -r t; do
        [[ -z "$t" ]] && continue
        folder="$(python3 -c "print(''.join(w.capitalize() for w in '$t'.split('-')))")"
        mkdir -p "$HOME/Pictures/Wallpapers/$folder/Animated"
    done < <("$HOME/.local/bin/qs-palette" list 2>/dev/null)
    ok "theme folders ready"
fi

# ============================================================
# 6. Apply the theme — this generates every derived file
# ============================================================

say "Applying theme: $THEME"
if "$HOME/.local/bin/qs-theme" "$THEME"; then
    ok "qs-theme finished"
else
    warn "qs-theme partially failed (a package may be missing)"
fi

# ============================================================
# 7. Apply the font everywhere
# ============================================================

# config/quickshell/font.conf ships the choice; qs-font pushes it into GTK,
# Qt, kitty, dunst, hyprlock and gsettings, none of which read that file
# themselves.
say "Applying fonts"
FONT_MONO="$(sed -n 's/^[[:space:]]*mono[[:space:]]*=[[:space:]]*//p' \
    "$HOME/.config/quickshell/font.conf" 2>/dev/null | head -1)"
FONT_UI="$(sed -n 's/^[[:space:]]*ui[[:space:]]*=[[:space:]]*//p' \
    "$HOME/.config/quickshell/font.conf" 2>/dev/null | head -1)"
FONT_MONO="${FONT_MONO:-JetBrainsMono Nerd Font}"
FONT_UI="${FONT_UI:-$FONT_MONO}"

if "$HOME/.local/bin/qs-font" "$FONT_MONO" "$FONT_UI" >/dev/null; then
    ok "fonts set to $FONT_MONO"
else
    warn "qs-font failed — is the font package installed?"
fi

# ============================================================
# 8. Summary
# ============================================================

say "Installation complete"

if ((${#FAILED[@]})); then
    printf '\n\033[1;33mWarnings:\033[0m\n'
    printf '  · %s\n' "${FAILED[@]}"
fi

cat <<'TXT'

  Next steps
  ──────────
  1. Log out and back into Hyprland.
     The GTK_THEME variable and the autostart entries only take effect in a
     fresh session; before that, GTK apps will not follow the theme.

  2. Optional — if YouTube Music Desktop is installed, theme its title bar:
       sudo ~/.local/bin/qs-ytmd-titlebar

  3. Optional — if Zen Browser is installed, restart it so the colours apply
     (userChrome.css is only read at startup).

  4. Optional — dual boot with Windows. The launcher's "Boot to Windows" entry
     needs a password-free root path, since it writes an EFI variable:
       sudo ~/.local/bin/qs-boot-windows --install
     If Windows has no EFI entry of its own, add it to the GRUB menu first:
       sudo ~/.local/bin/qs-grub-windows

  Keybindings
  ───────────
  Alt+Space       launcher             Super+V         clipboard history
  Super+Shift+S   screenshot           Super+Shift+Z   wallpaper picker
  Super+Ctrl+Z    theme picker         Super+H         gapless mode
  Super+Shift+P   performance mode     Super+F         fullscreen
  Super+Q         terminal             Super+B         browser

  Adding a theme
  ──────────────
  Add one block to ~/.config/quickshell/palettes.json — the bar, GTK, Qt/
  Kvantum, kitty, dunst, btop, Hyprland borders, Zen Browser and YouTube
  Music all read their colours from that single file.

  See PROJECT.md for how everything fits together and for the environment
  gotchas that are easy to trip over again.
TXT
