-- File: lua/lemon/highlights.lua
--
-- Turns a palette (lua/lemon/palette.lua) into the full highlight table.
-- One mapping serves every theme in palettes.json, so a new theme block gets a
-- matching editor for free and all of them look like the same editor.
--
-- The role assignment is fixed on purpose — mauve is the accent, blue the
-- function color, green strings — because the palettes keep their keys in the
-- same roles the bar uses them in. On Monochrome, where every accent is a
-- shade of grey, this comes out as a tonal scheme rather than a broken one.
-- The one exception is `distinct()` below, for palettes that give two keys the
-- same hex.

local Palette = require("lemon.palette")

local M = {}

---@param p table palette from lemon.palette
---@return table<string, table> highlight groups
function M.build(p)
  local blend = Palette.blend
  local light = Palette.luminance(p.base) > 0.5

  -- Some palettes spend one hex on two keys: Everforest's `mauve` and `green`
  -- are the same green, Gruvbox's `mauve` and `pink` the same rose. That is
  -- harmless in the bar, where those two never sit next to each other, but in
  -- code it makes keywords indistinguishable from strings. Fall through to the
  -- first alternative that is genuinely a different color.
  ---@param preferred string
  ---@param clashes string[] colors `preferred` must not equal
  ---@param alternatives string[] tried in order
  ---@return string
  local function distinct(preferred, clashes, alternatives)
    local function collides(color)
      for _, other in ipairs(clashes) do
        if color:lower() == other:lower() then
          return true
        end
      end
      return false
    end

    if not collides(preferred) then
      return preferred
    end
    for _, alternative in ipairs(alternatives) do
      if not collides(alternative) then
        return alternative
      end
    end
    return preferred
  end

  -- Semantic names, so the group table below reads as intent rather than color.
  local c = {
    bg = p.base,
    bg_dark = p.mantle, -- statusline, tabline, sidebars
    bg_darkest = p.crust, -- the strip behind everything
    bg_float = p.mantle,
    bg_sel = p.selected,
    bg_hover = p.hover,
    bg_hl = p.surface0, -- cursorline, folds, visual
    bg_danger = p.dangerBg,
    border = p.divider,
    border_strong = p.surface1,

    fg = p.text,
    fg_dim = p.subtext0,
    fg_dimmer = p.overlay0,
    fg_bright = p.subtext1,
    muted = p.surface2, -- non-text, indent guides

    accent = p.mauve,
    fn = p.blue,
    str = p.green,
    num = p.peach,
    type = p.yellow,
    op = p.cyan,
    special = p.pink,
    error = p.red,
    warn = p.yellow,
    info = p.blue,
    hint = p.cyan,
    ok = p.green,
  }

  -- `accent` stays the palette's accent whatever happens — it is the bar's
  -- accent and the UI has to agree with it. Only the syntax roles move.
  c.kw = distinct(p.mauve, { c.str }, { p.red, p.pink, p.peach, p.blue })
  c.special = distinct(p.pink, { c.kw, c.str }, { p.cyan, p.peach, p.blue })

  -- Derived tints. Blending against the editor background keeps these readable
  -- on light palettes too, where a flat 20% of green would wash out.
  local tint = function(color, amount)
    return blend(color, c.bg, amount)
  end
  local diff = {
    add = tint(c.str, light and 0.22 or 0.16),
    change = tint(c.type, light and 0.22 or 0.16),
    delete = tint(c.error, light and 0.22 or 0.16),
    text = tint(c.type, light and 0.34 or 0.28),
  }
  local search_bg = tint(c.type, 0.55)
  local cur_search_bg = tint(c.num, 0.75)

  local none = "NONE"

  --stylua: ignore
  local hl = {
    -- ── Editor ────────────────────────────────────────────────────────────
    Normal                 = { fg = c.fg, bg = c.bg },
    NormalNC               = { fg = c.fg, bg = c.bg },
    NormalFloat            = { fg = c.fg, bg = c.bg_float },
    FloatBorder            = { fg = c.border_strong, bg = c.bg_float },
    FloatTitle             = { fg = c.accent, bg = c.bg_float, bold = true },
    FloatFooter            = { fg = c.fg_dimmer, bg = c.bg_float },
    ColorColumn            = { bg = c.bg_dark },
    Conceal                = { fg = c.fg_dimmer },
    Cursor                 = { fg = c.bg, bg = c.fg },
    lCursor                = { fg = c.bg, bg = c.fg },
    CursorIM               = { fg = c.bg, bg = c.fg },
    TermCursor             = { fg = c.bg, bg = c.fg },
    CursorColumn           = { bg = c.bg_hl },
    CursorLine             = { bg = c.bg_sel },
    CursorLineNr           = { fg = c.accent, bold = true },
    CursorLineSign         = { bg = c.bg_sel },
    CursorLineFold         = { bg = c.bg_sel },
    LineNr                 = { fg = c.muted },
    LineNrAbove            = { fg = c.muted },
    LineNrBelow            = { fg = c.muted },
    SignColumn             = { fg = c.muted, bg = none },
    FoldColumn             = { fg = c.muted, bg = none },
    Folded                 = { fg = c.fn, bg = c.bg_hl },
    Directory              = { fg = c.fn },
    EndOfBuffer            = { fg = c.bg },
    ErrorMsg               = { fg = c.error, bold = true },
    WarningMsg             = { fg = c.warn },
    ModeMsg                = { fg = c.fg, bold = true },
    MoreMsg                = { fg = c.fn },
    MsgArea                = { fg = c.fg },
    MsgSeparator           = { fg = c.border, bg = c.bg_dark },
    Question               = { fg = c.str },
    NonText                = { fg = c.muted },
    SpecialKey             = { fg = c.muted },
    Whitespace             = { fg = c.muted },
    MatchParen             = { fg = c.num, bold = true },
    IncSearch              = { fg = c.bg, bg = c.num, bold = true },
    CurSearch              = { fg = c.bg, bg = cur_search_bg, bold = true },
    Search                 = { fg = c.fg, bg = search_bg },
    Substitute             = { fg = c.bg, bg = c.error },
    QuickFixLine           = { bg = c.bg_sel, bold = true },
    Visual                 = { bg = c.bg_hl },
    VisualNOS              = { bg = c.bg_hl },
    StatusLine             = { fg = c.fg, bg = c.bg_dark },
    StatusLineNC           = { fg = c.fg_dimmer, bg = c.bg_dark },
    TabLine                = { fg = c.fg_dim, bg = c.bg_dark },
    TabLineFill            = { bg = c.bg_darkest },
    TabLineSel             = { fg = c.accent, bg = c.bg, bold = true },
    WinBar                 = { fg = c.fg_dim, bg = none },
    WinBarNC               = { fg = c.fg_dimmer, bg = none },
    WinSeparator           = { fg = c.border, bg = none },
    VertSplit              = { fg = c.border, bg = none },
    Pmenu                  = { fg = c.fg, bg = c.bg_float },
    PmenuSel               = { fg = c.fg, bg = c.bg_sel, bold = true },
    PmenuKind              = { fg = c.accent, bg = c.bg_float },
    PmenuKindSel           = { fg = c.accent, bg = c.bg_sel },
    PmenuExtra             = { fg = c.fg_dimmer, bg = c.bg_float },
    PmenuExtraSel          = { fg = c.fg_dim, bg = c.bg_sel },
    PmenuSbar              = { bg = c.bg_dark },
    PmenuThumb             = { bg = c.border_strong },
    PmenuMatch             = { fg = c.accent, bold = true },
    PmenuMatchSel          = { fg = c.accent, bg = c.bg_sel, bold = true },
    WildMenu               = { fg = c.bg, bg = c.accent },
    Title                  = { fg = c.accent, bold = true },
    SpellBad               = { sp = c.error, undercurl = true },
    SpellCap               = { sp = c.warn, undercurl = true },
    SpellLocal             = { sp = c.info, undercurl = true },
    SpellRare              = { sp = c.hint, undercurl = true },
    DiffAdd                = { bg = diff.add },
    DiffChange             = { bg = diff.change },
    DiffDelete             = { bg = diff.delete },
    DiffText               = { bg = diff.text },
    Added                  = { fg = c.str },
    Changed                = { fg = c.type },
    Removed                = { fg = c.error },
    Debug                  = { fg = c.num },
    debugPC                = { bg = c.bg_dark },
    debugBreakpoint        = { fg = c.error, bg = c.bg_dark },

    -- ── Legacy syntax ─────────────────────────────────────────────────────
    Comment                = { fg = c.fg_dimmer, italic = true },
    Constant               = { fg = c.num },
    String                 = { fg = c.str },
    Character              = { fg = c.str },
    Number                 = { fg = c.num },
    Boolean                = { fg = c.num },
    Float                  = { fg = c.num },
    Identifier             = { fg = c.fg },
    Function               = { fg = c.fn },
    Statement              = { fg = c.kw },
    Conditional            = { fg = c.kw },
    Repeat                 = { fg = c.kw },
    Label                  = { fg = c.special },
    Operator               = { fg = c.op },
    Keyword                = { fg = c.kw, italic = true },
    Exception              = { fg = c.kw },
    PreProc                = { fg = c.special },
    Include                = { fg = c.kw },
    Define                 = { fg = c.special },
    Macro                  = { fg = c.special },
    PreCondit              = { fg = c.special },
    Type                   = { fg = c.type },
    StorageClass           = { fg = c.type },
    Structure              = { fg = c.type },
    Typedef                = { fg = c.type },
    Special                = { fg = c.special },
    SpecialChar            = { fg = c.special },
    Tag                    = { fg = c.kw },
    Delimiter              = { fg = c.fg_dim },
    SpecialComment         = { fg = c.fg_dim, italic = true },
    Underlined             = { fg = c.fn, underline = true },
    Bold                   = { bold = true },
    Italic                 = { italic = true },
    Ignore                 = { fg = c.fg_dimmer },
    Error                  = { fg = c.error },
    Todo                   = { fg = c.bg, bg = c.type, bold = true },

    -- ── Treesitter ────────────────────────────────────────────────────────
    ["@variable"]                    = { fg = c.fg },
    ["@variable.builtin"]            = { fg = c.error, italic = true },
    ["@variable.parameter"]          = { fg = c.num, italic = true },
    ["@variable.parameter.builtin"]  = { fg = c.num, italic = true },
    ["@variable.member"]             = { fg = c.fn },
    ["@constant"]                    = { fg = c.num },
    ["@constant.builtin"]            = { fg = c.num, italic = true },
    ["@constant.macro"]              = { fg = c.special },
    ["@module"]                      = { fg = c.type, italic = true },
    ["@module.builtin"]              = { fg = c.type, italic = true },
    ["@label"]                       = { fg = c.special },
    ["@string"]                      = { fg = c.str },
    ["@string.documentation"]        = { fg = c.str, italic = true },
    ["@string.regexp"]               = { fg = c.special },
    ["@string.escape"]               = { fg = c.special, bold = true },
    ["@string.special"]              = { fg = c.special },
    ["@string.special.symbol"]       = { fg = c.num },
    ["@string.special.path"]         = { fg = c.fn, underline = true },
    ["@string.special.url"]          = { fg = c.fn, underline = true },
    ["@character"]                   = { fg = c.str },
    ["@character.special"]           = { fg = c.special },
    ["@boolean"]                     = { fg = c.num },
    ["@number"]                      = { fg = c.num },
    ["@number.float"]                = { fg = c.num },
    ["@type"]                        = { fg = c.type },
    ["@type.builtin"]                = { fg = c.type, italic = true },
    ["@type.definition"]             = { fg = c.type },
    ["@attribute"]                   = { fg = c.type },
    ["@attribute.builtin"]           = { fg = c.type, italic = true },
    ["@property"]                    = { fg = c.fn },
    ["@function"]                    = { fg = c.fn },
    ["@function.builtin"]            = { fg = c.num, italic = true },
    ["@function.call"]               = { fg = c.fn },
    ["@function.macro"]              = { fg = c.special },
    ["@function.method"]             = { fg = c.fn },
    ["@function.method.call"]        = { fg = c.fn },
    ["@constructor"]                 = { fg = c.type },
    ["@operator"]                    = { fg = c.op },
    ["@keyword"]                     = { fg = c.kw, italic = true },
    ["@keyword.coroutine"]           = { fg = c.kw, italic = true },
    ["@keyword.function"]            = { fg = c.kw, italic = true },
    ["@keyword.operator"]            = { fg = c.kw },
    ["@keyword.import"]              = { fg = c.kw },
    ["@keyword.type"]                = { fg = c.kw },
    ["@keyword.modifier"]            = { fg = c.kw },
    ["@keyword.repeat"]              = { fg = c.kw },
    ["@keyword.return"]              = { fg = c.kw, italic = true },
    ["@keyword.debug"]               = { fg = c.error },
    ["@keyword.exception"]           = { fg = c.kw },
    ["@keyword.conditional"]         = { fg = c.kw },
    ["@keyword.conditional.ternary"] = { fg = c.op },
    ["@keyword.directive"]           = { fg = c.special },
    ["@keyword.directive.define"]    = { fg = c.special },
    ["@punctuation.delimiter"]       = { fg = c.fg_dim },
    ["@punctuation.bracket"]         = { fg = c.fg_dim },
    ["@punctuation.special"]         = { fg = c.special },
    ["@comment"]                     = { fg = c.fg_dimmer, italic = true },
    ["@comment.documentation"]       = { fg = c.fg_dim, italic = true },
    ["@comment.error"]               = { fg = c.bg, bg = c.error, bold = true },
    ["@comment.warning"]             = { fg = c.bg, bg = c.warn, bold = true },
    ["@comment.todo"]                = { fg = c.bg, bg = c.accent, bold = true },
    ["@comment.note"]                = { fg = c.bg, bg = c.hint, bold = true },
    ["@markup.strong"]               = { fg = c.fg, bold = true },
    ["@markup.italic"]               = { fg = c.fg, italic = true },
    ["@markup.strikethrough"]        = { fg = c.fg_dim, strikethrough = true },
    ["@markup.underline"]            = { underline = true },
    ["@markup.heading"]              = { fg = c.accent, bold = true },
    ["@markup.heading.1"]            = { fg = c.accent, bold = true },
    ["@markup.heading.2"]            = { fg = c.num, bold = true },
    ["@markup.heading.3"]            = { fg = c.type, bold = true },
    ["@markup.heading.4"]            = { fg = c.str, bold = true },
    ["@markup.heading.5"]            = { fg = c.op, bold = true },
    ["@markup.heading.6"]            = { fg = c.fn, bold = true },
    ["@markup.quote"]                = { fg = c.fg_dim, italic = true },
    ["@markup.math"]                 = { fg = c.fn },
    ["@markup.link"]                 = { fg = c.special },
    ["@markup.link.label"]           = { fg = c.fn },
    ["@markup.link.url"]             = { fg = c.op, underline = true },
    ["@markup.raw"]                  = { fg = c.str },
    ["@markup.raw.block"]            = { fg = c.str },
    ["@markup.list"]                 = { fg = c.op },
    ["@markup.list.checked"]         = { fg = c.str },
    ["@markup.list.unchecked"]       = { fg = c.fg_dim },
    ["@diff.plus"]                   = { fg = c.str, bg = diff.add },
    ["@diff.minus"]                  = { fg = c.error, bg = diff.delete },
    ["@diff.delta"]                  = { fg = c.type, bg = diff.change },
    ["@tag"]                         = { fg = c.kw },
    ["@tag.builtin"]                 = { fg = c.kw },
    ["@tag.attribute"]               = { fg = c.type, italic = true },
    ["@tag.delimiter"]               = { fg = c.fg_dim },

    -- ── LSP semantic tokens ───────────────────────────────────────────────
    ["@lsp.type.namespace"]      = { link = "@module" },
    ["@lsp.type.type"]           = { link = "@type" },
    ["@lsp.type.class"]          = { link = "@type" },
    ["@lsp.type.enum"]           = { link = "@type" },
    ["@lsp.type.interface"]      = { link = "@type" },
    ["@lsp.type.struct"]         = { link = "@type" },
    ["@lsp.type.typeParameter"]  = { link = "@type.definition" },
    ["@lsp.type.parameter"]      = { link = "@variable.parameter" },
    ["@lsp.type.variable"]       = { link = "@variable" },
    ["@lsp.type.property"]       = { link = "@property" },
    ["@lsp.type.enumMember"]     = { link = "@constant" },
    ["@lsp.type.function"]       = { link = "@function" },
    ["@lsp.type.method"]         = { link = "@function.method" },
    ["@lsp.type.macro"]          = { link = "@function.macro" },
    ["@lsp.type.decorator"]      = { link = "@attribute" },
    ["@lsp.type.keyword"]        = { link = "@keyword" },
    ["@lsp.type.comment"]        = { link = "@comment" },
    ["@lsp.type.string"]         = { link = "@string" },
    ["@lsp.type.number"]         = { link = "@number" },
    ["@lsp.type.operator"]       = { link = "@operator" },
    ["@lsp.type.selfKeyword"]    = { link = "@variable.builtin" },
    ["@lsp.type.lifetime"]       = { link = "@keyword.modifier" },
    ["@lsp.typemod.function.defaultLibrary"] = { link = "@function.builtin" },
    ["@lsp.typemod.variable.defaultLibrary"] = { link = "@variable.builtin" },
    ["@lsp.typemod.variable.readonly"]       = { link = "@constant" },
    ["@lsp.typemod.keyword.async"]           = { link = "@keyword.coroutine" },
    ["@lsp.mod.deprecated"]                  = { strikethrough = true },

    -- ── Diagnostics ───────────────────────────────────────────────────────
    DiagnosticError            = { fg = c.error },
    DiagnosticWarn             = { fg = c.warn },
    DiagnosticInfo             = { fg = c.info },
    DiagnosticHint             = { fg = c.hint },
    DiagnosticOk               = { fg = c.ok },
    DiagnosticVirtualTextError = { fg = c.error, bg = tint(c.error, 0.12) },
    DiagnosticVirtualTextWarn  = { fg = c.warn, bg = tint(c.warn, 0.12) },
    DiagnosticVirtualTextInfo  = { fg = c.info, bg = tint(c.info, 0.12) },
    DiagnosticVirtualTextHint  = { fg = c.hint, bg = tint(c.hint, 0.12) },
    DiagnosticVirtualTextOk    = { fg = c.ok, bg = tint(c.ok, 0.12) },
    DiagnosticUnderlineError   = { sp = c.error, undercurl = true },
    DiagnosticUnderlineWarn    = { sp = c.warn, undercurl = true },
    DiagnosticUnderlineInfo    = { sp = c.info, undercurl = true },
    DiagnosticUnderlineHint    = { sp = c.hint, undercurl = true },
    DiagnosticUnderlineOk      = { sp = c.ok, undercurl = true },
    DiagnosticSignError        = { fg = c.error },
    DiagnosticSignWarn         = { fg = c.warn },
    DiagnosticSignInfo         = { fg = c.info },
    DiagnosticSignHint         = { fg = c.hint },
    DiagnosticFloatingError    = { fg = c.error },
    DiagnosticFloatingWarn     = { fg = c.warn },
    DiagnosticFloatingInfo     = { fg = c.info },
    DiagnosticFloatingHint     = { fg = c.hint },
    DiagnosticDeprecated       = { sp = c.fg_dimmer, strikethrough = true },
    DiagnosticUnnecessary      = { fg = c.fg_dimmer },

    -- ── LSP ───────────────────────────────────────────────────────────────
    LspReferenceText            = { bg = c.bg_hl },
    LspReferenceRead            = { bg = c.bg_hl },
    LspReferenceWrite           = { bg = c.bg_hl, underline = true },
    LspSignatureActiveParameter = { fg = c.num, bold = true },
    LspInlayHint                = { fg = c.fg_dimmer, bg = c.bg_dark, italic = true },
    LspCodeLens                 = { fg = c.fg_dimmer, italic = true },
    LspInfoBorder               = { link = "FloatBorder" },

    -- ── gitsigns ──────────────────────────────────────────────────────────
    GitSignsAdd          = { fg = c.str },
    GitSignsChange       = { fg = c.type },
    GitSignsDelete       = { fg = c.error },
    GitSignsAddInline    = { bg = diff.add },
    GitSignsChangeInline = { bg = diff.change },
    GitSignsDeleteInline = { bg = diff.delete },
    GitSignsCurrentLineBlame = { fg = c.fg_dimmer, italic = true },

    -- ── neo-tree ──────────────────────────────────────────────────────────
    NeoTreeNormal          = { fg = c.fg_dim, bg = c.bg_dark },
    NeoTreeNormalNC        = { fg = c.fg_dim, bg = c.bg_dark },
    NeoTreeEndOfBuffer     = { fg = c.bg_dark, bg = c.bg_dark },
    NeoTreeWinSeparator    = { fg = c.border, bg = c.border },
    NeoTreeTitleBar        = { fg = c.bg, bg = c.accent, bold = true },
    NeoTreeFloatBorder     = { link = "FloatBorder" },
    NeoTreeFloatTitle      = { link = "FloatTitle" },
    NeoTreeRootName        = { fg = c.accent, bold = true },
    NeoTreeDirectoryName   = { fg = c.fn },
    NeoTreeDirectoryIcon   = { fg = c.fn },
    NeoTreeFileName        = { fg = c.fg_dim },
    NeoTreeFileIcon        = { fg = c.fg_dim },
    NeoTreeFileNameOpened  = { fg = c.accent },
    NeoTreeSymbolicLinkTarget = { fg = c.special },
    NeoTreeIndentMarker    = { fg = c.muted },
    NeoTreeExpander        = { fg = c.fg_dimmer },
    NeoTreeCursorLine      = { bg = c.bg_sel },
    NeoTreeDimText         = { fg = c.fg_dimmer },
    NeoTreeDotfile         = { fg = c.fg_dimmer },
    NeoTreeHiddenByName    = { fg = c.fg_dimmer },
    NeoTreeModified        = { fg = c.num },
    NeoTreeGitAdded        = { fg = c.str },
    NeoTreeGitConflict     = { fg = c.error, bold = true },
    NeoTreeGitDeleted      = { fg = c.error },
    NeoTreeGitIgnored      = { fg = c.fg_dimmer },
    NeoTreeGitModified     = { fg = c.type },
    NeoTreeGitUnstaged     = { fg = c.num },
    NeoTreeGitUntracked    = { fg = c.special },
    NeoTreeGitStaged       = { fg = c.str },
    NeoTreeTabActive       = { fg = c.accent, bg = c.bg_dark, bold = true },
    NeoTreeTabInactive     = { fg = c.fg_dimmer, bg = c.bg_darkest },
    NeoTreeTabSeparatorActive   = { fg = c.bg_dark, bg = c.bg_dark },
    NeoTreeTabSeparatorInactive = { fg = c.bg_darkest, bg = c.bg_darkest },

    -- ── telescope ─────────────────────────────────────────────────────────
    TelescopeNormal         = { fg = c.fg, bg = c.bg_float },
    TelescopeBorder         = { fg = c.border_strong, bg = c.bg_float },
    TelescopeTitle          = { fg = c.bg, bg = c.accent, bold = true },
    TelescopePromptNormal   = { fg = c.fg, bg = c.bg_hl },
    TelescopePromptBorder   = { fg = c.bg_hl, bg = c.bg_hl },
    TelescopePromptTitle    = { fg = c.bg, bg = c.accent, bold = true },
    TelescopePromptPrefix   = { fg = c.accent },
    TelescopePromptCounter  = { fg = c.fg_dimmer },
    TelescopeResultsNormal  = { fg = c.fg_dim, bg = c.bg_float },
    TelescopeResultsBorder  = { fg = c.border_strong, bg = c.bg_float },
    TelescopeResultsTitle   = { fg = c.bg_float, bg = c.bg_float },
    TelescopePreviewNormal  = { fg = c.fg, bg = c.bg_float },
    TelescopePreviewBorder  = { fg = c.border_strong, bg = c.bg_float },
    TelescopePreviewTitle   = { fg = c.bg, bg = c.str, bold = true },
    TelescopeSelection      = { fg = c.fg, bg = c.bg_sel, bold = true },
    TelescopeSelectionCaret = { fg = c.accent, bg = c.bg_sel },
    TelescopeMultiSelection = { fg = c.num, bg = c.bg_sel },
    TelescopeMatching       = { fg = c.accent, bold = true },

    -- ── bufferline ────────────────────────────────────────────────────────
    BufferLineFill                    = { bg = c.bg_darkest },
    BufferLineBackground              = { fg = c.fg_dimmer, bg = c.bg_dark },
    BufferLineBufferVisible           = { fg = c.fg_dim, bg = c.bg_dark },
    BufferLineBufferSelected          = { fg = c.accent, bg = c.bg, bold = true, italic = false },
    BufferLineTab                     = { fg = c.fg_dimmer, bg = c.bg_dark },
    BufferLineTabSelected             = { fg = c.accent, bg = c.bg, bold = true },
    BufferLineTabSeparator            = { fg = c.bg_darkest, bg = c.bg_dark },
    BufferLineTabSeparatorSelected    = { fg = c.bg_darkest, bg = c.bg },
    BufferLineTabClose                = { fg = c.error, bg = c.bg_darkest },
    BufferLineSeparator               = { fg = c.bg_darkest, bg = c.bg_dark },
    BufferLineSeparatorVisible        = { fg = c.bg_darkest, bg = c.bg_dark },
    BufferLineSeparatorSelected       = { fg = c.bg_darkest, bg = c.bg },
    BufferLineIndicatorVisible        = { fg = c.bg_dark, bg = c.bg_dark },
    BufferLineIndicatorSelected       = { fg = c.accent, bg = c.bg },
    BufferLineModified                = { fg = c.num, bg = c.bg_dark },
    BufferLineModifiedVisible         = { fg = c.num, bg = c.bg_dark },
    BufferLineModifiedSelected        = { fg = c.num, bg = c.bg },
    BufferLineCloseButton             = { fg = c.fg_dimmer, bg = c.bg_dark },
    BufferLineCloseButtonVisible      = { fg = c.fg_dim, bg = c.bg_dark },
    BufferLineCloseButtonSelected     = { fg = c.error, bg = c.bg },
    BufferLineDuplicate               = { fg = c.fg_dimmer, bg = c.bg_dark, italic = true },
    BufferLineDuplicateVisible        = { fg = c.fg_dim, bg = c.bg_dark, italic = true },
    BufferLineDuplicateSelected       = { fg = c.accent, bg = c.bg, italic = true },
    BufferLineOffsetSeparator         = { fg = c.border, bg = c.bg_dark },
    BufferLineErrorDiagnostic         = { fg = c.error, bg = c.bg_dark },
    BufferLineErrorDiagnosticVisible  = { fg = c.error, bg = c.bg_dark },
    BufferLineErrorDiagnosticSelected = { fg = c.error, bg = c.bg, bold = true },
    BufferLineWarningDiagnostic       = { fg = c.warn, bg = c.bg_dark },
    BufferLineWarningDiagnosticVisible = { fg = c.warn, bg = c.bg_dark },
    BufferLineWarningDiagnosticSelected = { fg = c.warn, bg = c.bg, bold = true },
    BufferLineInfoDiagnostic          = { fg = c.info, bg = c.bg_dark },
    BufferLineInfoDiagnosticVisible   = { fg = c.info, bg = c.bg_dark },
    BufferLineInfoDiagnosticSelected  = { fg = c.info, bg = c.bg, bold = true },
    BufferLineHintDiagnostic          = { fg = c.hint, bg = c.bg_dark },
    BufferLineHintDiagnosticVisible   = { fg = c.hint, bg = c.bg_dark },
    BufferLineHintDiagnosticSelected  = { fg = c.hint, bg = c.bg, bold = true },

    -- ── nvim-cmp ──────────────────────────────────────────────────────────
    CmpItemAbbr              = { fg = c.fg_dim },
    CmpItemAbbrDeprecated    = { fg = c.fg_dimmer, strikethrough = true },
    CmpItemAbbrMatch         = { fg = c.accent, bold = true },
    CmpItemAbbrMatchFuzzy    = { fg = c.accent, bold = true },
    CmpItemMenu              = { fg = c.fg_dimmer, italic = true },
    CmpItemKindText          = { fg = c.fg_dim },
    CmpItemKindMethod        = { fg = c.fn },
    CmpItemKindFunction      = { fg = c.fn },
    CmpItemKindConstructor   = { fg = c.type },
    CmpItemKindField         = { fg = c.op },
    CmpItemKindVariable      = { fg = c.fg },
    CmpItemKindClass         = { fg = c.type },
    CmpItemKindInterface     = { fg = c.type },
    CmpItemKindModule        = { fg = c.type },
    CmpItemKindProperty      = { fg = c.op },
    CmpItemKindUnit          = { fg = c.num },
    CmpItemKindValue         = { fg = c.num },
    CmpItemKindEnum          = { fg = c.type },
    CmpItemKindKeyword       = { fg = c.accent },
    CmpItemKindSnippet       = { fg = c.special },
    CmpItemKindColor         = { fg = c.special },
    CmpItemKindFile          = { fg = c.fn },
    CmpItemKindReference     = { fg = c.error },
    CmpItemKindFolder        = { fg = c.fn },
    CmpItemKindEnumMember    = { fg = c.num },
    CmpItemKindConstant      = { fg = c.num },
    CmpItemKindStruct        = { fg = c.type },
    CmpItemKindEvent         = { fg = c.special },
    CmpItemKindOperator      = { fg = c.op },
    CmpItemKindTypeParameter = { fg = c.type },

    -- ── nvim-notify / noice ───────────────────────────────────────────────
    NotifyERRORBorder = { fg = c.error, bg = c.bg_float },
    NotifyWARNBorder  = { fg = c.warn, bg = c.bg_float },
    NotifyINFOBorder  = { fg = c.info, bg = c.bg_float },
    NotifyDEBUGBorder = { fg = c.fg_dimmer, bg = c.bg_float },
    NotifyTRACEBorder = { fg = c.special, bg = c.bg_float },
    NotifyERRORIcon   = { fg = c.error },
    NotifyWARNIcon    = { fg = c.warn },
    NotifyINFOIcon    = { fg = c.info },
    NotifyDEBUGIcon   = { fg = c.fg_dimmer },
    NotifyTRACEIcon   = { fg = c.special },
    NotifyERRORTitle  = { fg = c.error, bold = true },
    NotifyWARNTitle   = { fg = c.warn, bold = true },
    NotifyINFOTitle   = { fg = c.info, bold = true },
    NotifyDEBUGTitle  = { fg = c.fg_dimmer, bold = true },
    NotifyTRACETitle  = { fg = c.special, bold = true },
    NotifyERRORBody   = { fg = c.fg, bg = c.bg_float },
    NotifyWARNBody    = { fg = c.fg, bg = c.bg_float },
    NotifyINFOBody    = { fg = c.fg, bg = c.bg_float },
    NotifyDEBUGBody   = { fg = c.fg, bg = c.bg_float },
    NotifyTRACEBody   = { fg = c.fg, bg = c.bg_float },
    NotifyBackground  = { bg = c.bg_float },

    NoiceCmdline               = { fg = c.fg, bg = c.bg_float },
    NoiceCmdlineIcon           = { fg = c.accent },
    NoiceCmdlineIconSearch     = { fg = c.num },
    NoiceCmdlinePopup          = { fg = c.fg, bg = c.bg_float },
    NoiceCmdlinePopupBorder    = { fg = c.accent, bg = c.bg_float },
    NoiceCmdlinePopupTitle     = { fg = c.accent, bold = true },
    NoiceCmdlinePopupBorderSearch = { fg = c.num, bg = c.bg_float },
    NoiceCmdlinePrompt         = { fg = c.accent },
    NoiceConfirm               = { fg = c.fg, bg = c.bg_float },
    NoiceConfirmBorder         = { fg = c.accent, bg = c.bg_float },
    NoicePopup                 = { fg = c.fg, bg = c.bg_float },
    NoicePopupBorder           = { fg = c.border_strong, bg = c.bg_float },
    NoicePopupmenu             = { fg = c.fg, bg = c.bg_float },
    NoicePopupmenuBorder       = { fg = c.border_strong, bg = c.bg_float },
    NoicePopupmenuMatch        = { fg = c.accent, bold = true },
    NoicePopupmenuSelected     = { fg = c.fg, bg = c.bg_sel },
    NoiceMini                  = { fg = c.fg_dim, bg = c.bg_dark },
    NoiceLspProgressTitle      = { fg = c.fg_dim },
    NoiceLspProgressClient     = { fg = c.accent, bold = true },
    NoiceLspProgressSpinner    = { fg = c.op },
    NoiceVirtualText           = { fg = c.accent },
    NoiceFormatProgressDone    = { fg = c.bg, bg = c.str },
    NoiceFormatProgressTodo    = { fg = c.fg_dim, bg = c.bg_hl },

    -- ── todo-comments / trouble / flash ───────────────────────────────────
    TodoBgTODO  = { fg = c.bg, bg = c.info, bold = true },
    TodoFgTODO  = { fg = c.info },
    TodoSignTODO = { fg = c.info },
    TodoBgFIX   = { fg = c.bg, bg = c.error, bold = true },
    TodoFgFIX   = { fg = c.error },
    TodoSignFIX = { fg = c.error },
    TodoBgHACK  = { fg = c.bg, bg = c.warn, bold = true },
    TodoFgHACK  = { fg = c.warn },
    TodoSignHACK = { fg = c.warn },
    TodoBgWARN  = { fg = c.bg, bg = c.warn, bold = true },
    TodoFgWARN  = { fg = c.warn },
    TodoSignWARN = { fg = c.warn },
    TodoBgPERF  = { fg = c.bg, bg = c.accent, bold = true },
    TodoFgPERF  = { fg = c.accent },
    TodoSignPERF = { fg = c.accent },
    TodoBgNOTE  = { fg = c.bg, bg = c.hint, bold = true },
    TodoFgNOTE  = { fg = c.hint },
    TodoSignNOTE = { fg = c.hint },
    TodoBgTEST  = { fg = c.bg, bg = c.special, bold = true },
    TodoFgTEST  = { fg = c.special },
    TodoSignTEST = { fg = c.special },

    TroubleNormal      = { fg = c.fg_dim, bg = c.bg_dark },
    TroubleNormalNC    = { fg = c.fg_dim, bg = c.bg_dark },
    TroubleText        = { fg = c.fg_dim },
    TroubleCount       = { fg = c.accent, bg = c.bg_hl },
    TroubleFoldIcon    = { fg = c.fg_dimmer },
    TroubleIndent      = { fg = c.muted },
    TroubleLocation    = { fg = c.fg_dimmer },
    TroubleSource      = { fg = c.fg_dimmer, italic = true },
    TroubleCode        = { fg = c.fg_dimmer },
    TroubleFile        = { fg = c.fn, bold = true },
    TroublePreview     = { bg = c.bg_sel },

    FlashBackdrop = { fg = c.fg_dimmer },
    FlashLabel    = { fg = c.bg, bg = c.error, bold = true },
    FlashMatch    = { fg = c.fg, bg = c.bg_hl },
    FlashCurrent  = { fg = c.bg, bg = c.num, bold = true },

    -- ── alpha / lazy / mason / toggleterm ─────────────────────────────────
    AlphaHeader   = { fg = c.accent, bold = true },
    AlphaButtons  = { fg = c.fn },
    AlphaShortcut = { fg = c.num, bold = true },
    AlphaFooter   = { fg = c.fg_dimmer, italic = true },

    LazyNormal        = { fg = c.fg, bg = c.bg_float },
    LazyH1            = { fg = c.bg, bg = c.accent, bold = true },
    LazyH2            = { fg = c.accent, bold = true },
    LazyButton        = { fg = c.fg_dim, bg = c.bg_hl },
    LazyButtonActive  = { fg = c.bg, bg = c.accent, bold = true },
    LazySpecial       = { fg = c.op },
    LazyProgressDone  = { fg = c.str, bold = true },
    LazyProgressTodo  = { fg = c.muted, bold = true },
    LazyCommit        = { fg = c.str },
    LazyProp          = { fg = c.fg_dim },
    LazyReasonPlugin  = { fg = c.special },
    LazyReasonEvent   = { fg = c.num },
    LazyReasonKeys    = { fg = c.op },
    LazyReasonStart   = { fg = c.fg_dimmer },
    LazyReasonRuntime = { fg = c.type },
    LazyReasonCmd     = { fg = c.type },
    LazyReasonFt      = { fg = c.fn },
    LazyReasonSource  = { fg = c.op },
    LazyReasonImport  = { fg = c.fg_dim },
    LazyDimmed        = { fg = c.fg_dimmer },

    MasonNormal              = { fg = c.fg, bg = c.bg_float },
    MasonHeader              = { fg = c.bg, bg = c.accent, bold = true },
    MasonHeaderSecondary     = { fg = c.bg, bg = c.fn, bold = true },
    MasonHighlight           = { fg = c.accent },
    MasonHighlightBlock      = { fg = c.bg, bg = c.accent },
    MasonHighlightBlockBold  = { fg = c.bg, bg = c.accent, bold = true },
    MasonMuted               = { fg = c.fg_dimmer },
    MasonMutedBlock          = { fg = c.fg_dim, bg = c.bg_hl },
    MasonError               = { fg = c.error },
    MasonWarning             = { fg = c.warn },

    ToggleTerm       = { fg = c.fg, bg = c.bg },
    ToggleTermNormal = { fg = c.fg, bg = c.bg },
    ToggleTermBorder = { fg = c.accent, bg = c.bg },

    -- ── LuaSnip / misc ────────────────────────────────────────────────────
    LuasnipInsertNodeActive = { fg = c.num, bold = true },
    LuasnipChoiceNodeActive = { fg = c.op, bold = true },
    healthError   = { fg = c.error },
    healthSuccess = { fg = c.str },
    healthWarning = { fg = c.warn },
    qfLineNr      = { fg = c.fg_dimmer },
    qfFileName    = { fg = c.fn },
  }

  return hl, c
end

---Terminal colors, matching the `color0..15` block `qs-theme` writes for kitty
---so :terminal and the outer terminal agree.
---@param p table
---@return table<string, string>
function M.terminal(p)
  return {
    terminal_color_0 = p.surface1,
    terminal_color_8 = p.surface2,
    terminal_color_1 = p.red,
    terminal_color_9 = p.red,
    terminal_color_2 = p.green,
    terminal_color_10 = p.green,
    terminal_color_3 = p.yellow,
    terminal_color_11 = p.yellow,
    terminal_color_4 = p.blue,
    terminal_color_12 = p.blue,
    terminal_color_5 = p.pink,
    terminal_color_13 = p.pink,
    terminal_color_6 = p.cyan,
    terminal_color_14 = p.cyan,
    terminal_color_7 = p.subtext0,
    terminal_color_15 = p.text,
  }
end

return M
