
require("config.animations")
require("config.autostart")
require("config.colors")
require("config.cursor")
require("config.decorations")
require("config.defaults")
require("config.environment")
require("config.input")
require("config.keybinds")
require("config.misc")
require("config.monitors")
require("config.windowrules")
require("config.keyring")
-- EN SONDA: performans modu açıksa yukarıdaki değerleri eziyor.
-- Böylece `hyprctl reload` modu iptal etmiyor. (bkz. qs-mode)
require("config.perfmode")
