
hl.on("hyprland.start", function ()
    hl.exec_cmd("dbus-update-activation-environment --systemd --all")
    hl.exec_cmd("xhost +SI:localuser:root")
    hl.exec_cmd("hyprpaper")
    hl.exec_cmd(os.getenv("HOME") .. "/.local/bin/qs-wallpaper restore")
    hl.exec_cmd("quickshell -c topbar")
    hl.exec_cmd(os.getenv("HOME") .. "/.local/bin/qs-wallpaper-watch")
    hl.exec_cmd("gsetting set org.desktop.interface gtk-theme 'KvArcDark'")
    hl.exec_cmd("gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'")
    hl.exec_cmd("wl-paste --type text --watch cliphist store")
    hl.exec_cmd("wl-paste --type image --watch cliphist store")
    hl.exec_cmd("wl-clip-persist --clipboard regular")
    hl.exec_cmd("dunst")
    hl.exec_cmd(os.getenv("HOME") .. "/.local/bin/dunst-icon-cache")
    hl.exec_cmd(os.getenv("HOME") .. "/.local/bin/qs-notif-dismiss-watch")
end)
